services:
  torrserver:
    image: ghcr.io/yourok/torrserver:latest
    restart: unless-stopped
    environment:
      - TS_PORT=8090
      - TS_DONTKILL=1
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    expose:
      - "8090"
    volumes:
      - torrserver-config:/opt/ts/config
      - torrserver-cache:/opt/ts/torrents

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    expose:
      - "9117"
    volumes:
      - jackett-config:/config

volumes:
  torrserver-config:
  torrserver-cache:
  jackett-config:
